name: 'Create release'
description: 'Create a release based on package version'
author: 'G-Network'
inputs:
  relese:
    description: 'Create release (true/false)'
    required: false
  deploy:
    description: 'Run deployment(true/false)'
    required: false
  type:
    description: 'Deployment type(package/service)'
    required: false
  awsKey:
    description: 'AWS Key'
    required: false
  awsSecret:
    description: 'AWS Secret'
    required: false
outputs:
  version:
    description: 'New release version or false if no release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
